packages:
  - apps/*
  - packages/*
  - examples/*

onlyBuiltDependencies:
  - sharp

ignoredBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
  - unrs-resolver
